### ISSUE TITLE
Issue #1 - User can see their car

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML page
- [x] Create CSS and link sheet
- [x] Create and link JS script
- [x] Add car to body
- [x] Remove extraneous CSS
- [x] Debug
