### ISSUE TITLE
Issue #2 - User can turn their car

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create CSS classes of car for up, right, down, left
- [x] Create JS function that changes class of car based on key pressed
- [x] Add event listener with aforementioned function as callback
- [x] Remove extraneous CSS
- [x] Debug
