### ISSUE TITLE
Issue #3 - User can start their car

### ISSUE THREAD

**Issue by ry-zhao** [ry-zhao/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create JS function that moves car a few pixels
- [x] Create event listener that listens for when the space key is pressed
- [x] Create a function that set interval that calls the first function every 16 seconds
- [x] Pass it to the event listener
- [x] Remove extraneous CSS
- [x] Debug
